version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "silverstreet"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17ugvnmlirl61"
s3_prefix = "silverstreet"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
